---
- name: Enable Epel on RedHat OS family (RH6)
  yum: name={{ epel6_url }}
       state=present
  when: ansible_distribution_major_version == "6"

- name: Enable Epel on RedHat OS family (RH7)
  yum: name={{ epel7_url }}
       state=present
  when: ansible_distribution_major_version == "7"

- name: Install CollectD on RedHat OS family
  yum: name={{ item.package }} 
       state=latest
  with_items: collectd_packages

- name: Copy main CollectD Configuration on RedHat OS family
  template: src=collectd.conf.j2
            dest={{ collectd_conf_rh }}
            backup=yes
            owner=root
            group=root
            mode=0644
  notify: restart collectd
  tags:
   - configure

- name: Copy Includes CollectD Configurations on RedHat OS family
  template: src=collectd.include.conf.j2
            dest={{ collectd_include_rh }}/{{ item.plugin }}.include.conf
            backup=yes
            owner=root
            group=root
            mode=0644
  with_items: collectd_plugins
  when: item.type is defined and item.type == "include"
  notify: restart collectd
  tags:
   - configure
